### ISSUE TITLE
Options with empty value are not visible

### ISSUE THREAD

**Issue by EtienneDelepine** [jarstone/dselect#1]
Hi, thank you very much for this amazing JS!
The problem I'm facing is when a SELECT has an empty OPTION (e.g. "Choose from the list...") where the value is an empty string, it doesn't appear in the choices. So it is impossible to remove a selection once 1 choice has been made.
If the value is "0" it appears, but obviously the script receiving the form thinks there is something (0 is not "").
Is there a way to let appear the options with empty value ?

THANK YOU!

**Comment by jarstone** [comment]
Hi,
By default, the empty option is used as the "placeholder".
You can clear the selection with the "clearable" option, so that the empty option can appear again.

Example:
```html
<select class="form-select" id="example">
  <option value="">Choose from the list...</option>
  <option value="chrome">Chrome</option>
  <option value="firefox">Firefox</option>
  <option value="safari">Safari</option>
  <option value="edge">Edge</option>
  <option value="opera">Opera</option>
  <option value="brave">Brave</option>
</select>
```

```javascript
dselect(document.querySelector('#example'), {
  clearable: true
})
```

**Comment by EtienneDelepine** [comment]
👍 Thank you, I didn't understood what this option was for! I had to test by myself instead of boring you 😕
Very useful library!
